// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIVEkp-Oouw6sq8U49veaJ1IvdQeLrh0M',
    appId: '1:1097286765540:web:6a2598cd67dd6b278e15f1',
    messagingSenderId: '1097286765540',
    projectId: 'kondrups-d7ef5',
    authDomain: 'kondrups-d7ef5.firebaseapp.com',
    storageBucket: 'kondrups-d7ef5.firebasestorage.app',
    measurementId: 'G-Z3WZBWT9MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkKDCPZiYkgRuKyheLPBHgbAa0qIAOvxM',
    appId: '1:1097286765540:android:3a07c16cbfcf8b068e15f1',
    messagingSenderId: '1097286765540',
    projectId: 'kondrups-d7ef5',
    storageBucket: 'kondrups-d7ef5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh5CYIjxnbCp7K8LUoeULgUnlfpkqd4Jo',
    appId: '1:1097286765540:ios:e76efc5c0b209ec08e15f1',
    messagingSenderId: '1097286765540',
    projectId: 'kondrups-d7ef5',
    storageBucket: 'kondrups-d7ef5.firebasestorage.app',
    iosBundleId: 'dk.kondrups.relationsappKlient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh5CYIjxnbCp7K8LUoeULgUnlfpkqd4Jo',
    appId: '1:1097286765540:ios:e76efc5c0b209ec08e15f1',
    messagingSenderId: '1097286765540',
    projectId: 'kondrups-d7ef5',
    storageBucket: 'kondrups-d7ef5.firebasestorage.app',
    iosBundleId: 'dk.kondrups.relationsappKlient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIVEkp-Oouw6sq8U49veaJ1IvdQeLrh0M',
    appId: '1:1097286765540:web:a56515c008af68648e15f1',
    messagingSenderId: '1097286765540',
    projectId: 'kondrups-d7ef5',
    authDomain: 'kondrups-d7ef5.firebaseapp.com',
    storageBucket: 'kondrups-d7ef5.firebasestorage.app',
    measurementId: 'G-T4SR44JB23',
  );
}
